In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Country-Series - Metadata.csv to Country-Series - Metadata (1).csv
Saving IDS_ALLCountries_Data.csv to IDS_ALLCountries_Data (1).csv
Saving IDS_CountryMetaData.csv to IDS_CountryMetaData (1).csv
Saving IDS_FootNoteMetaData.csv to IDS_FootNoteMetaData (1).csv
Saving IDS_SeriesMetaData.csv to IDS_SeriesMetaData (1).csv

In [ ]:
import pandas as pd

# 1. Main debt data
df_data = pd.read_csv("IDS_ALLCountries_Data.csv", encoding="latin1")
print("Main data:", df_data.shape)
display(df_data)
df_data.describe()

Main data: (62983, 39)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62981,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62982,Last Updated: 12/03/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
count,4.949000e+04,4.943400e+04,4.926200e+04,4.900100e+04,4.919500e+04,4.913700e+04,4.939400e+04,4.964500e+04,4.949700e+04,4.976800e+04,...,5.064100e+04,5.059000e+04,1.285500e+04,1.276000e+04,1.262200e+04,1.243200e+04,1.213800e+04,1.196700e+04,1.177100e+04,1.156600e+04
mean,3.632014e+09,3.589615e+09,3.659750e+09,4.109777e+09,4.536444e+09,4.738496e+09,5.190393e+09,6.182575e+09,6.752879e+09,6.849177e+09,...,1.649637e+10,1.736519e+10,6.308260e+09,5.571382e+09,5.184003e+09,4.809777e+09,4.085452e+09,5.141240e+09,3.242091e+09,2.706323e+09
std,5.292695e+10,5.308864e+10,5.449395e+10,6.107004e+10,7.054690e+10,8.035767e+10,9.357806e+10,1.147883e+11,1.365185e+11,1.357978e+11,...,3.389385e+11,3.512324e+11,3.737201e+10,3.200925e+10,2.969469e+10,2.622276e+10,2.201532e+10,3.087435e+10,1.687863e+10,1.380838e+10
min,-8.487669e+10,-5.573282e+10,-7.292274e+10,-5.500037e+10,-3.736228e+10,-7.343440e+10,-7.145644e+10,-5.255350e+10,-6.940197e+10,-4.432376e+10,...,-2.590000e+11,-2.320000e+11,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.112442e+00,3.541816e-01,7.421391e-01,1.116054e-01,5.356484e-01,7.739000e-01,9.361400e-01,2.862026e+00,3.052400e+00,5.876775e+00,...,0.000000e+00,0.000000e+00,1.819800e+07,1.736757e+07,1.692255e+07,1.508966e+07,1.359342e+07,1.182594e+07,1.033100e+07,8.062213e+06
50%,9.046966e+06,8.033068e+06,7.674301e+06,8.706365e+06,9.689430e+06,9.915805e+06,1.046313e+07,1.172750e+07,1.261500e+07,1.515973e+07,...,3.397000e+07,3.286379e+07,1.747302e+08,1.683518e+08,1.612748e+08,1.386245e+08,1.220880e+08,1.077675e+08,9.936185e+07,8.007778e+07
75%,1.725729e+08,1.660500e+08,1.715300e+08,1.868751e+08,2.174472e+08,2.195815e+08,2.196477e+08,2.781230e+08,2.915208e+08,3.518703e+08,...,7.984620e+08,8.363163e+08,1.275588e+09,1.228297e+09,1.142909e+09,9.780040e+08,8.999615e+08,7.999839e+08,8.112449e+08,6.457404e+08
max,5.440000e+12,5.450000e+12,5.560000e+12,6.220000e+12,7.290000e+12,8.580000e+12,1.010000e+13,1.250000e+13,1.490000e+13,1.490000e+13,...,3.680000e+13,3.820000e+13,1.170000e+12,1.000000e+12,9.180000e+11,7.740000e+11,6.570000e+11,7.330000e+11,4.810000e+11,3.820000e+11

In [ ]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62983 entries, 0 to 62982
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           62980 non-null  object
 1   Country Code           62978 non-null  object
 2   Counterpart-Area Name  62978 non-null  object
 3   Counterpart-Area Code  62978 non-null  object
 4   Series Name            62978 non-null  object
 5   Series Code            62978 non-null  object
 6   2000                   49490 non-null  float64
 7   2001                   49434 non-null  float64
 8   2002                   49262 non-null  float64
 9   2003                   49001 non-null  float64
 10  2004                   49195 non-null  float64
 11  2005                   49137 non-null  float64
 12  2006                   49394 non-null  float64
 13  2007                   49645 non-null  float64
 14  2008                   49497 non-null  float64
 15  2009                   49768 non-null  float64
 16  2010                   49761 non-null  float64
 17  2011                   49080 non-null  float64
 18  2012                   49008 non-null  float64
 19  2013                   49379 non-null  float64
 20  2014                   50504 non-null  float64
 21  2015                   50431 non-null  float64
 22  2016                   50192 non-null  float64
 23  2017                   50333 non-null  float64
 24  2018                   50296 non-null  float64
 25  2019                   50493 non-null  float64
 26  2020                   50956 non-null  float64
 27  2021                   50727 non-null  float64
 28  2022                   50721 non-null  float64
 29  2023                   50641 non-null  float64
 30  2024                   50590 non-null  float64
 31  2025                   12855 non-null  float64
 32  2026                   12760 non-null  float64
 33  2027                   12622 non-null  float64
 34  2028                   12432 non-null  float64
 35  2029                   12138 non-null  float64
 36  2030                   11967 non-null  float64
 37  2031                   11771 non-null  float64
 38  2032                   11566 non-null  float64
dtypes: float64(33), object(6)
memory usage: 18.7+ MB

In [ ]:
#drop columns from 2025 t0 2032:
df_data.drop(df_data.loc[:, '2025':'2032'].columns, axis=1, inplace=True)
print(df_data.columns.tolist()) #check if the columns are droped

['Country Name', 'Country Code', 'Counterpart-Area Name', 'Counterpart-Area Code', 'Series Name', 'Series Code', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [ ]:
print("Shape:", df_data.shape)
print("\nColumns:", df_data.columns.tolist())
print("\nData types:\n", df_data.dtypes)
print("\nMissing values per column:\n", df_data.isnull().sum())
print("\nDuplicate rows:", df_data.duplicated().sum())

Shape: (62983, 31)

Columns: ['Country Name', 'Country Code', 'Counterpart-Area Name', 'Counterpart-Area Code', 'Series Name', 'Series Code', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

Data types:
 Country Name              object
Country Code              object
Counterpart-Area Name     object
Counterpart-Area Code     object
Series Name               object
Series Code               object
2000                     float64
2001                     float64
2002                     float64
2003                     float64
2004                     float64
2005                     float64
2006                     float64
2007                     float64
2008                     float64
2009                     float64
2010                     float64
2011                     float64
2012                     float64
2013                     float64
2014                     float64
2015                     float64
2016                     float64
2017                     float64
2018                     float64
2019                     float64
2020                     float64
2021                     float64
2022                     float64
2023                     float64
2024                     float64
dtype: object

Missing values per column:
 Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2000                     13493
2001                     13549
2002                     13721
2003                     13982
2004                     13788
2005                     13846
2006                     13589
2007                     13338
2008                     13486
2009                     13215
2010                     13222
2011                     13903
2012                     13975
2013                     13604
2014                     12479
2015                     12552
2016                     12791
2017                     12650
2018                     12687
2019                     12490
2020                     12027
2021                     12256
2022                     12262
2023                     12342
2024                     12393
dtype: int64

Duplicate rows: 2

In [ ]:
 #Drop useless columns
df_data = df_data.drop(columns=['Counterpart-Area Name', 'Counterpart-Area Code'])
#Drop duplicate rows
df_data = df_data.drop_duplicates()
print("Duplicates:", df_data.duplicated().sum())
print(df_data.isnull().sum())

Duplicates: 0
Country Name        1
Country Code        3
Series Name         3
Series Code         3
2000            13491
2001            13547
2002            13719
2003            13980
2004            13786
2005            13844
2006            13587
2007            13336
2008            13484
2009            13213
2010            13220
2011            13901
2012            13973
2013            13602
2014            12477
2015            12550
2016            12789
2017            12648
2018            12685
2019            12488
2020            12025
2021            12254
2022            12260
2023            12340
2024            12391
dtype: int64

In [ ]:
#Drop rows with missing identifiers (broken rows)
df_data = df_data.dropna(subset=['Country Name', 'Country Code'])
print("Shape after cleanup:", df_data.shape)

Shape after cleanup: (62978, 29)

In [ ]:
year_cols = [str(y) for y in range(2000, 2025)]
id_cols = ['Country Name', 'Country Code', 'Series Name', 'Series Code']

long_df = df_data.melt(
    id_vars=id_cols,
    value_vars=year_cols,
    var_name='Year',
    value_name='Value'
)

# Drop rows where there's no value for that year (this is where the ~13k/year nulls get handled)

long_df['Year'] = long_df['Year'].astype(int)

# Sort so years are in order within each group before filling
long_df = long_df.sort_values(['Country Name', 'Series Code', 'Year'])

# Forward-fill Value within each Country + Series group only
long_df['Value'] = long_df.groupby(['Country Name', 'Series Code'])['Value'].ffill()

#backward fill value after forward fill to drop null
long_df['Value'] = long_df.groupby(['Country Name', 'Series Code'])['Value'].bfill()

#Handle series with zero historical data across all years
long_df['Value'] = long_df['Value'].fillna(0)

display("Long format shape:", long_df.shape)
display(long_df.head(5))
print("Nulls:\n", long_df.isnull().sum())

'Long format shape:'

(1574450, 6)

,Country Name,Country Code,Series Name,Series Code,Year,Value
112,Afghanistan,AFG,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2000,3.873397e+09
63090,Afghanistan,AFG,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2001,3.873397e+09
126068,Afghanistan,AFG,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2002,3.873397e+09
189046,Afghanistan,AFG,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2003,3.873397e+09
252024,Afghanistan,AFG,"Imports of goods, services and primary income ...",BM.GSR.TOTL.CD,2004,3.873397e+09

Nulls:
 Country Name    0
Country Code    0
Series Name     0
Series Code     0
Year            0
Value           0
dtype: int64

In [ ]:
long_df.to_csv("IDS_ALLCountries_Data_cleaned.csv", index=False)

2. Footnote metadata

In [ ]:
# 2. Footnote metadata
df_footnote = pd.read_csv("IDS_FootNoteMetaData.csv", encoding="latin1")
display("Footnote metadata:", df_footnote.shape)
display(df_footnote.head(5))
print("null:",df_footnote.isnull().sum())

'Footnote metadata:'

(2673, 5)

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...

null: Type            0
Country Code    0
Series Code     0
Time Code       0
Description     0
dtype: int64

In [ ]:
# Split  Country Name, Country Code
country_split = df_footnote['Country Code'].str.extract(r'^(.*)\s\(([^()]+)\)$')
df_footnote['Country Name'] = country_split[0]
df_footnote['Country Code'] = country_split[1]

In [ ]:
# Split "Full indicator name (CODE)" -> Series Name, Series Code
series_split = df_footnote['Series Code'].str.extract(r'^(.*)\s\(([^()]+)\)$')
df_footnote['Series Name'] = series_split[0]
df_footnote['Series Code'] = series_split[1]

In [ ]:
# Extract just the year from "2023 (YR2023)" -> 2023 (int)
df_footnote['Time Code'] = df_footnote['Time Code'].str.extract(r'^(\d{4})').astype(int)
df_footnote = df_footnote.rename(columns={'Time Code': 'Year'})

In [ ]:
# Reorder columns
df_footnote = df_footnote[
    ['Type', 'Country Name', 'Country Code', 'Series Name', 'Series Code', 'Year', 'Description']
]
display("Footnote metadata after split:", df_footnote.shape)
display(df_footnote.head())
print("Nulls:\n", df_footnote.isnull().sum())

'Footnote metadata after split:'

(2673, 7)

,Type,Country Name,Country Code,Series Name,Series Code,Year,Description
0,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,BX.TRF.PWKR.CD.DT,2024,Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,BX.TRF.PWKR.CD.DT,2023,Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,BX.TRF.PWKR.CD.DT,2021,Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,BX.TRF.PWKR.CD.DT,2022,Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan,AFG,"Foreign direct investment, net inflows in repo...",BX.KLT.DINV.CD.DT,2021,Source: United Nations Conference on Trade and...

Nulls:
 Type            0
Country Name    0
Country Code    0
Series Name     0
Series Code     0
Year            0
Description     0
dtype: int64

In [ ]:
df_footnote.to_csv("IDS_FootNoteMetaData_cleaned.csv", index=False)

3.country-series metadata

In [ ]:
# 3. Country-Series metadata (use the exact filename you uploaded)
df_country_series = pd.read_csv("Country-Series - Metadata.csv", encoding="latin1")
display("Country-Series metadata:", df_country_series.shape)
display(df_country_series.head(6))
print("null:",df_country_series.isnull().sum())

'Country-Series metadata:'

(375, 4)

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...
2,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed, long..."
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Angola (AGO),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...
5,Country-Series,Angola (AGO),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...

null: Type            0
Country Code    0
Series Code     0
Description     0
dtype: int64

In [ ]:
#separate country name,code
country_split = df_country_series['Country Code'].str.extract(r'^(.*)\s\(([^()]+)\)$')
df_country_series['Country Name'] = country_split[0]
df_country_series['Country Code'] = country_split[1]

In [ ]:
#separate series name,code
series_split =df_country_series['Series Code'].str.extract(r'^(.*)\s\(([^()]+)\)$')
df_country_series['Series Name'] = series_split[0]
df_country_series['Series Code'] = series_split[1]

In [ ]:
df_country_series =df_country_series[['Type', 'Country Name', 'Country Code', 'Series Name', 'Series Code', 'Description']]
display("\nCountry-Series metadata after split:", df_country_series.shape)
display(df_country_series.head())
print("Nulls:\n", df_country_series.isnull().sum())

'\nCountry-Series metadata after split:'

(375, 6)

,Type,Country Name,Country Code,Series Name,Series Code,Description
0,Country-Series,Afghanistan,AFG,"Foreign direct investment, net inflows in repo...",BX.KLT.DINV.CD.DT,Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan,AFG,"Population, total",SP.POP.TOTL,Data source: United Nations World Population P...
2,Country-Series,Afghanistan,AFG,"External debt stocks, total (DOD, current US$)",DT.DOD.DECT.CD,"Long-term public and publicly guaranteed, long..."
3,Country-Series,Angola,AGO,"External debt stocks, total (DOD, current US$)",DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
4,Country-Series,Angola,AGO,"Population, total",SP.POP.TOTL,Data source: United Nations World Population P...

Nulls:
 Type            0
Country Name    0
Country Code    0
Series Name     0
Series Code     0
Description     0
dtype: int64

In [ ]:
df_country_series.to_csv("Country-Series_Metadata_cleaned.csv", index=False)

4.country metadata

In [ ]:
# 4. Country metadata
df_country = pd.read_csv("IDS_CountryMetaData.csv", encoding="latin1")
display("Country metadata:", df_country.shape)
display(df_country.head(6))
print("null:",df_country.isnull().sum())

'Country metadata:'

(134, 30)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa,IDA,HIPC,Afghan afghani,1979,Multiple Indicator Cluster Survey 2022-2023,The reporting period for national accounts dat...,...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2023,Demographic and Health Survey 2017 - 2018,NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2022,Multiple Indicator Cluster Survey 2018-2019,NaN,...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,Demographic and Health Survey 2015/16,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2022,Multiple Indicator Cluster Survey 2019-2020,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina
5,ARM,Republic of Armenia,Upper middle income,Europe & Central Asia,IBRD,NaN,Armenian dram,2011,Demographic and Health Survey 2015-2016,NaN,...,"Integrated household survey (IHS), 2016",Yes,2014,NaN,2018.0,2012.0,AM,AM,Armenia,Armenia

null: Code                                                  0
Long Name                                             0
Income Group                                         15
Region                                               14
Lending category                                     14
Other groups                                         94
Currency Unit                                        14
Latest population census                             16
Latest household survey                              14
Special Notes                                        74
National accounts base year                          14
National accounts reference year                     95
System of National Accounts                          14
SNA price valuation                                  14
PPP survey years                                     18
Balance of Payments Manual in use                    16
External debt Reporting status                       14
System of trade                                      34
Government Accounting concept                        37
IMF data dissemination standard                      17
Source of most recent Income and expenditure data    18
Vital registration complete                          98
Latest agricultural census                           63
Latest industrial data                               49
Latest trade data                                    21
Latest water withdrawal data                         22
2-alpha code                                          0
WB-2 code                                             0
Table Name                                            0
Short Name                                            0
dtype: int64

In [ ]:
display(df_country.columns.tolist())
print("Duplicates in df_country:", df_country.duplicated().sum())

['Code',
 'Long Name',
 'Income Group',
 'Region',
 'Lending category',
 'Other groups',
 'Currency Unit',
 'Latest population census',
 'Latest household survey',
 'Special Notes',
 'National accounts base year',
 'National accounts reference year',
 'System of National Accounts',
 'SNA price valuation',
 'PPP survey years',
 'Balance of Payments Manual in use',
 'External debt Reporting status',
 'System of trade',
 'Government Accounting concept',
 'IMF data dissemination standard',
 'Source of most recent Income and expenditure data',
 'Vital registration complete',
 'Latest agricultural census',
 'Latest industrial data',
 'Latest trade data',
 'Latest water withdrawal data',
 '2-alpha code',
 'WB-2 code',
 'Table Name',
 'Short Name']

Duplicates in df_country: 0

In [ ]:
countries = df_country[['Code', 'Short Name', 'Region', 'Income Group']].copy()
countries = countries.rename(columns={'Code': 'Country Code', 'Short Name': 'Country Name'})
display(countries.columns.tolist())
print("Nulls:\n", countries.isnull().sum())

['Country Code', 'Country Name', 'Region', 'Income Group']

Nulls:
 Country Code     0
Country Name     0
Region          14
Income Group    15
dtype: int64

In [ ]:
#Forward fill across all columns in the dataset
countries = countries.ffill()
print(countries.isnull().sum())

Country Code    0
Country Name    0
Region          0
Income Group    0
dtype: int64

In [ ]:
#Backward fill to catch any initial NaNs at index 0 (e.g., columns starting with missing values)
countries = countries.bfill()
print(countries.isnull().sum())
print(countries.head(5))

Country Code    0
Country Name    0
Region          0
Income Group    0
dtype: int64
  Country Code Country Name                      Region         Income Group
0          AFG  Afghanistan  Middle East & North Africa           Low income
1          ALB      Albania       Europe & Central Asia  Upper middle income
2          DZA      Algeria  Middle East & North Africa  Upper middle income
3          AGO       Angola          Sub-Saharan Africa  Lower middle income
4          ARG    Argentina   Latin America & Caribbean  Upper middle income

In [ ]:
# Save the cleaned countries metadata
countries.to_csv("IDS_CountryMetaData_cleaned.csv", index=False)

5.series metadata

In [ ]:
# 5. Series/indicator metadata
df_series = pd.read_csv("IDS_SeriesMetaData.csv", encoding="latin1")
display("Series metadata:", df_series.shape)
display(df_series.head(6))
print("null values:",df_series.isnull().sum())

'Series metadata:'

(574, 12)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
5,DT.GRE.PRVT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN

null values: Code                            0
License Type                  572
Indicator Name                  0
Short definition                2
Long definition                 0
Source                          0
Topic                           0
Dataset                         1
Periodicity                     0
Aggregation method              0
Limitations and exceptions    573
General comments              566
dtype: int64

In [ ]:
# Select  columns
indicators = df_series[['Code', 'Indicator Name', 'Topic', 'Periodicity', 'Aggregation method']].copy()

# Rename columns for SQL standardization
indicators = indicators.rename(columns={
    'Code': 'Indicator Code',
    'Indicator Name': 'Indicator Name',
    'Topic': 'Topic',
    'Periodicity': 'Periodicity',
    'Aggregation method': 'Aggregation Method'
})

In [ ]:
print("Nulls:\n", indicators.isnull().sum())
print(indicators.shape)

Nulls:
 Indicator Code        0
Indicator Name        0
Topic                 0
Periodicity           0
Aggregation Method    0
dtype: int64
(574, 5)

In [ ]:
print("duplicates:", indicators.duplicated().sum())
print(indicators.info())

duplicates: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Indicator Code      574 non-null    object
 1   Indicator Name      574 non-null    object
 2   Topic               574 non-null    object
 3   Periodicity         574 non-null    object
 4   Aggregation Method  574 non-null    object
dtypes: object(5)
memory usage: 22.6+ KB
None

In [ ]:
# Save cleaned series metadata
indicators.to_csv("IDS_SeriesMetaData_cleaned.csv", index=False)

EDA

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

# load cleaned data
df = pd.read_csv("IDS_ALLCountries_Data_cleaned.csv")
df["Country Code"] = df["Country Code"].str.strip()
df["Series Code"] = df["Series Code"].str.strip()

# Filter out World Bank regional/income aggregates (not real countries)
AGGREGATE_CODES = ['EAP', 'ECA', 'IDX', 'IDA', 'LAC', 'LDC', 'LMY',
                    'LIC', 'LMC', 'MNA', 'MIC', 'SAS', 'SSA', 'UMC',
                    'WLD', 'HIC', 'OED', 'PST', 'HPC', 'EAS',
                    'EAR', 'ECS', 'EMU', 'LTE', 'MEA', 'NAC', 'OSS',
                    'PRE', 'PSS', 'TEA', 'TEC', 'TLA', 'TMN', 'TSA', 'TSS']
df = df[~df["Country Code"].isin(AGGREGATE_CODES)]
print("Rows after filtering out aggregates:", df.shape)

# Key headline indicator: Total External Debt Stocks
TOTAL_DEBT = "External debt stocks, total (DOD, current US$)"
debt_total = df[df["Series Name"] == TOTAL_DEBT]
print("Rows for Total External Debt indicator:", debt_total.shape)

Rows after filtering out aggregates: (1376225, 6)
Rows for Total External Debt indicator: (3000, 6)

In [ ]:
latest_year = 2023
debt_latest = debt_total[debt_total["Year"] == latest_year]
country_debt = debt_latest.groupby("Country Name")["Value"].sum().sort_values(ascending=False)

1.country-wise debt distribution

In [ ]:

import pandas as pd
import plotly.express as px

# Convert country_debt Series to DataFrame with 'Country Name' and 'Value' columns
# This variable 'country_debt' is available from previously executed cells.
country_debt_df = country_debt.reset_index(name='Value')

# Top 10 countries by debt
top15 = country_debt_df.head(15)

fig_top15 = px.bar(top15, x="Country Name", y="Value", title=f"Top 15 Countries by Total External Debt ({latest_year})",
              labels={"Value": "Debt (current US$)"}, color_discrete_sequence=["steelblue"],
              hover_data={"Value": ":,.0f"})
fig_top15.update_layout(xaxis_tickangle=-45)
fig_top15.show()

2.top 10 vs bottom 10 countries

In [ ]:
import pandas as pd
import plotly.express as px
# 2. Top / bottom countries
# Convert country_debt Series to DataFrame with 'Country Name' and 'Value' columns
country_debt_df = country_debt.reset_index(name='Value')

top10 = country_debt_df.head(10)
bottom10 = country_debt_df[country_debt_df["Value"] > 0].tail(10)

fig2a = px.bar(top10, x="Country Name", y="Value", title=f"Top 10 Countries by Debt ({latest_year})",
              labels={"Value": "Debt (current US$)"}, color_discrete_sequence=["steelblue"])
fig2a.update_layout(xaxis_tickangle=-45)
fig2a.show()

fig2b = px.bar(bottom10, x="Country Name", y="Value", title=f"Bottom 10 Countries by Debt ({latest_year})",
               labels={"Value": "Debt (current US$)"}, color_discrete_sequence=["salmon"])
fig2b.update_layout(xaxis_tickangle=-45)
fig2b.show()

3.different debt indicators and their impact

In [ ]:
import plotly.express as px

# 3. Different debt indicators and their impact

print("3. DEBT INDICATORS AND THEIR IMPACT")

# 3a. Magnitude of actual DEBT-related indicators only (exclude GNI/Imports/Exports
#     which are economic context, not debt itself)
debt_keywords = ["debt", "DOD", "TDS", "arrears"]
debt_indicators_only = df[df["Series Name"].str.contains("debt", case=False, na=False)]
indicator_totals = (
    debt_indicators_only[debt_indicators_only["Year"] == latest_year]
    .groupby("Series Name")["Value"]
    .sum()
    .abs()
    .sort_values(ascending=False)
)
print("\nTop 10 debt-specific indicators by magnitude:")
print(indicator_totals.head(10))

# Convert Series to DataFrame for Plotly Express
df_top_indicators = indicator_totals.head(10).reset_index()

fig_3a = px.bar(
    df_top_indicators,
    x="Value",
    y="Series Name",
    orientation="h",
    color_discrete_sequence=["darkorange"],
    title=f"Top 10 Debt Indicators by Total Magnitude ({latest_year})",
    labels={
        "Value": "Total Value (absolute, current US$)",
        "Series Name": "Debt Indicator",
    },
)

# Invert y-axis to match matplotlib's top-down ranking
fig_3a.update_layout(
    yaxis={"autorange": "reversed"},
    template="plotly_white",
    margin=dict(l=150, r=20, t=50, b=50),
)
fig_3a.show()
# Save to interactive HTML file if needed:
# fig_3a.write_html("eda_2_top_indicators.html")


# 3b. IMPACT: Debt-to-GNI ratio - shows how burdensome debt actually is per country
gni = df[(df["Series Name"] == "GNI (current US$)") & (df["Year"] == latest_year)]
gni = gni[["Country Name", "Value"]].rename(columns={"Value": "GNI"})

debt_vs_gni = debt_latest[["Country Name", "Value"]].rename(
    columns={"Value": "Debt"}
)
impact_df = debt_vs_gni.merge(gni, on="Country Name")
impact_df["Debt_to_GNI_pct"] = (impact_df["Debt"] / impact_df["GNI"]) * 100
impact_df = impact_df.sort_values("Debt_to_GNI_pct", ascending=False)

print(
    "\nTop 10 countries by Debt-to-GNI ratio (most debt-burdened relative to economy size):"
)
print(impact_df[["Country Name", "Debt_to_GNI_pct"]].head(10).to_string(index=False))

fig_3b = px.bar(
    impact_df.head(10),
    x="Country Name",
    y="Debt_to_GNI_pct",
    color_discrete_sequence=["firebrick"],
    title=f"Top 10 Countries by Debt-to-GNI Ratio ({latest_year}) - Debt Burden Impact",
    labels={
        "Debt_to_GNI_pct": "Debt as % of GNI",
        "Country Name": "Country",
    },
    text_auto=".2f",  # Displays percentage labels on top of bars
)

fig_3b.update_layout(
    xaxis={"tickangle": -45}, template="plotly_white", margin=dict(t=50, b=100)
)
fig_3b.show()
# Save to interactive HTML file if needed:
# fig_3b.write_html("eda_2b_debt_to_gni.html")

3. DEBT INDICATORS AND THEIR IMPACT

Top 10 debt-specific indicators by magnitude:
Series Name
External debt stocks, total (DOD, current US$)                                   8.841006e+12
External debt stocks, long-term (DOD, current US$)                               6.121345e+12
External debt stocks, variable rate (DOD, current US$)                           3.748061e+12
External debt stocks, public and publicly guaranteed (PPG) (DOD, current US$)    3.473926e+12
External debt stocks, long-term public sector (DOD, current US$)                 3.453057e+12
External debt stocks, public sector (PPG) (DOD, current US$)                     3.451595e+12
Present value of external debt (current US$)                                     3.175648e+12
External debt stocks, long-term private sector (DOD, current US$)                2.668845e+12
External debt stocks, private nonguaranteed (PNG) (DOD, current US$)             2.648924e+12
External debt stocks, general government sector (PPG) (DOD, current US$)         2.596717e+12
Name: Value, dtype: float64

Top 10 countries by Debt-to-GNI ratio (most debt-burdened relative to economy size):
Country Name  Debt_to_GNI_pct
  Mozambique       355.368526
     Lebanon       331.649551
    Mongolia       193.629879
     Senegal       153.247351
    Suriname       130.295485
   Mauritius       123.586943
     Lao PDR       122.953017
      Bhutan       114.499504
  Montenegro       113.955221
      Zambia       110.675742

4.Patterns , trends,relationship

In [ ]:

# 4. Patterns, trends, AND relationships

#Global total external debt trend

yearly_trend = debt_total[debt_total["Year"] <= 2023].groupby("Year")["Value"].sum().reset_index()

fig4 = px.line(
    yearly_trend, x="Year", y="Value", markers=True,
    title="Global Total External Debt Trend (2000-2023)",
    labels={"Value": "Debt (current US$)"}
)
fig4.show()

top5_countries = country_debt_df.head(5)["Country Name"].tolist()
top5_trend = debt_total[(debt_total["Country Name"].isin(top5_countries)) & (debt_total["Year"] <= 2023)]

#Top 5 Most Indebted Countries (2000-2023)"
fig4a = px.line(
    top5_trend, x="Year", y="Value", color="Country Name", markers=True,
    title="External Debt Trend: Top 5 Most Indebted Countries (2000-2023)",
    labels={"Value": "Debt (current US$)"}
)
fig4a.show()

# 4b. RELATIONSHIPS: correlation between Debt, GNI, and Reserves
reserves = df[(df["Series Name"] == "Total reserves (includes gold, current US$)") & (df["Year"] == latest_year)]
reserves = reserves[["Country Name", "Value"]].rename(columns={"Value": "Reserves"})
relationship_df = impact_df.merge(reserves, on="Country Name", how="left")

corr_debt_gni = relationship_df["Debt"].corr(relationship_df["GNI"])
arr_debt_reserves = relationship_df["Debt"].corr(relationship_df["Reserves"])
print(f"Correlation between Debt and GNI: {corr_debt_gni:.3f}")
print(f"Correlation between Debt and Reserves: {arr_debt_reserves:.3f}")

fig4b = px.scatter(
    relationship_df, x="GNI", y="Debt", hover_name="Country Name",
    trendline="ols",
    title=f"Relationship: External Debt vs GNI ({latest_year}) — corr = {corr_debt_gni:.2f}",
    labels={"GNI": "GNI (current US$)", "Debt": "External Debt (current US$)"}
)
fig4b.show()

Correlation between Debt and GNI: 0.965
Correlation between Debt and Reserves: 0.922

5.statistical summaries and comparision

In [ ]:
import plotly.express as px

# 5. Statistical summaries and comparisons

print("5. STATISTICAL SUMMARY (Total External Debt, 2023)")

print(debt_latest["Value"].describe())

print("\nStandard deviation:", debt_latest["Value"].std())
print("Median:", debt_latest["Value"].median())
print("Skew:", debt_latest["Value"].skew())

# 5a. Boxplot to visualize spread/outliers
fig_5a = px.box(
    debt_latest,
    x="Value",
    points="outliers",
    title=f"Distribution of Total External Debt Across Countries ({latest_year})",
    labels={"Value": "Debt (current US$)"},
    color_discrete_sequence=["steelblue"],
)
fig_5a.update_layout(template="plotly_white", margin=dict(t=50, b=50))
fig_5a.show()
#fig_5a.write_html("eda_5_boxplot.html")


# 5b. COMPARISONS: across Region and Income Group
countries_meta = pd.read_csv("IDS_CountryMetaData_cleaned.csv")
countries_meta = countries_meta[
    ~countries_meta["Country Code"].str.strip().isin(AGGREGATE_CODES)
]

debt_with_meta = debt_latest.merge(countries_meta, on="Country Name", how="left")

print("\nAverage debt by Region:")
region_avg = (
    debt_with_meta.groupby("Region")["Value"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
print(region_avg.to_string(index=False))

# Bar chart by Region
fig_5b = px.bar(
    region_avg,
    x="Region",
    y="Value",
    title=f"Average External Debt by Region ({latest_year})",
    labels={"Value": "Average Debt (current US$)", "Region": "Region"},
    color_discrete_sequence=["teal"],
    text_auto=".2s",  # Shows formatted numbers (e.g., $1.2B) on top of bars
)
fig_5b.update_layout(
    xaxis={"tickangle": -45}, template="plotly_white", margin=dict(t=50, b=100)
)
fig_5b.show()
#fig_5b.write_html("eda_5b_region_comparison.html")


print("\nAverage debt by Income Group:")
income_avg = (
    debt_with_meta.groupby("Income Group")["Value"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
print(income_avg.to_string(index=False))

# Bar chart by Income Group
fig_5c = px.bar(
    income_avg,
    x="Income Group",
    y="Value",
    title=f"Average External Debt by Income Group ({latest_year})",
    labels={"Value": "Average Debt (current US$)", "Income Group": "Income Group"},
    color_discrete_sequence=["purple"],
    text_auto=".2s",
)
fig_5c.update_layout(
    xaxis={"tickangle": -45}, template="plotly_white", margin=dict(t=50, b=100)
)
fig_5c.show()
#fig_5c.write_html("eda_5c_income_comparison.html")

5. STATISTICAL SUMMARY (Total External Debt, 2023)
count    1.200000e+02
mean     7.367505e+10
std      2.477441e+11
min      1.964535e+08
25%      3.408008e+09
50%      1.252995e+10
75%      4.332234e+10
max      2.450000e+12
Name: Value, dtype: float64

Standard deviation: 247744066320.80768
Median: 12529954756.5
Skew: 7.870524200541881

Average debt by Region:
                    Region        Value
       East Asia & Pacific 2.137221e+11
                South Asia 1.377990e+11
 Latin America & Caribbean 9.493510e+10
Middle East & North Africa 3.932941e+10
     Europe & Central Asia 3.738243e+10
        Sub-Saharan Africa 1.988240e+10

Average debt by Income Group:
       Income Group        Value
Upper middle income 1.240578e+11
Lower middle income 4.922338e+10
         Low income 8.709974e+09
        High income 2.952575e+09